branch-defaults:
  fix/aws_dynamo:
    environment: Proyectoback-env
deploy:
  artifact: target/ProyectoBack-1.0.0.jar
environment-defaults:
  Proyectoback-env:
    branch: null
    repository: null
global:
  application_name: ProyectoBack
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Java 8 running on
    64bit Amazon Linux/2.8.2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
